### PR TITLE
adds workflow for deploying sample-service to dev0 cluster

### PR DESCRIPTION
**Pull request by punkle**
ch3494

### CODE REVIEW

**Comment by nicolasarnold12321** [comment]
Should we create a helmrelease k8s object like with roadie-backstage?

**Comment by punkle** [comment]
@nicolasarnold12321 I like the idea, but I think it adds a bit of complexity. I dont think we need the type of auto recovery and resiliance for this service. What do you think?

**Review by iain-b — APPROVED** [review]

**Comment by nicolasarnold12321** [comment]
> @nicolasarnold12321 I like the idea, but I think it adds a bit of complexity. I dont think we need the type of auto recovery and resiliance for this service. What do you think?

We could even just deploy it manually instead of having automation if you prefer. Whenever we make changes to chart in the future we just bump the chart version. I just don't really like the idea of github creating resources that's all.

**Comment by nicolasarnold12321** [comment]
If you're happy with that I don't mind approving!

Might be worth adding a change to the sample-service repo so that it is triggered.

**Comment by punkle** [comment]
ok cool. done. Ive deployed it manually. Ill close this.

**Pull request closed without merging**
